import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    { // Overview
      type: 'category',
      label: 'Feature Overview',
      items: [{type: 'autogenerated', dirName: 'overview'}]
    },
    { // Build Tutorials
      type: 'category',
      label: 'Build Tutorials',
      items: [
        { // Experiment Development
          type: 'category',
          label: 'Experiments',
          items: [
            'tutorials/rt-task',
            'tutorials/community-tutorials',
          ]
        },
        { // Plugin Development
          type: 'category',
          label: 'Plugins',
          items: [{type: 'autogenerated', dirName: 'developers'}]
        }
      ]
    }
  ],
  referenceSidebar: [
    { // Core
      type: 'category',
      label: 'Core Documentation',
      items: [{type: 'autogenerated', dirName: 'reference'}]
    },
    { // Extensions
      type: 'category',
      label: 'Extensions',
      items: [{type: 'autogenerated', dirName: 'extensions'}]
    },
    { // Plugins
      type: 'category',
      label: 'Plugins',
      items: [{type: 'autogenerated', dirName: 'plugins'}]
    }
  ],
  communitySidebar: [
    'support/support'
  ],
  aboutSidebar: [{type: 'autogenerated', dirName: 'about'}] // problem with loading license.md

  // pages that need sidebar home:
  // 'support/migration-v7'
  // 'support/migration-v8'

  // pages that break build:
  // 'plugins/'
  // 'newsletter'
  // 'extensions/mouse-tracking'
  // 'extensions/record-video'

  // content that needs writing:
  // 'timelines/'
  // plugins from jspsych-contrib
  // timeline tutorials
  // extension tutorials

  // pages left unused:
  // 'index'

};

export default sidebars;
