import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    { // For Researchers
      type: 'category',
      label: 'For Researchers',
      link: { // categories with autogenerated items seem to have use a __category__.json in the dir
        type: 'generated-index',
        title: 'Guides for Researchers',
        description: 'Learn everything you need to design an experiment in jsPsych',
        keywords: ['guides'],
      },
      items: [
        { // Experiment Development
          type: 'category',
          label: 'Tutorials',
          link: { // categories with autogenerated items seem to have use a __category__.json in the dir
            type: 'generated-index',
            title: 'Tutorials',
            description: 'Step-by-step tutorials and demos for building an experiment from scratch',
            keywords: ['guides'],
          },
          items: [
            {
              type: 'doc',
              id: 'tutorials/rt-task',
              label: 'Demo Experiment: Simple Reaction Time Task', 
              // can also change sidebar label with docs frontmatter property 'title'
              // - this allows user to keep 'autogenerated' item types
              // - without frontmatter property 'title' or sidebar `items[n].label`,
              //   label defaults to first markdown heading in doc.md
            },
            'tutorials/community-tutorials',
          ]
        },
        { // Overview
          type: 'category',
          label: 'Feature Overview',
          link: { // categories with autogenerated items seem to have use a __category__.json in the dir
            type: 'generated-index',
            title: 'Feature Overview',
            description: 'Every feature available for researchers to tailor their experiments',
            keywords: ['guides'],
          },
          // items here relabeled with docs frontmatter property 'title'
          items: [{type: 'autogenerated', dirName: 'overview'}]
        },
      ]
    },
    { // Build Tutorials
      type: 'category',
      label: 'For Developers',
      link: { // categories with autogenerated items seem to have use a __category__.json in the dir
        type: 'generated-index',
        title: 'Guides for Developers',
        description: 'Learn everything you need to develop a contribution for jsPsych',
        keywords: ['guides'], // look into what keywords do
      },
      items: [
        {
          type: 'doc',
          id: 'developers/configuration'
        },
        {
          type: 'doc',
          id: 'developers/contributing'
        },
        { // Plugin Development
          type: 'category',
          label: 'Plugins',
          link: { // categories with autogenerated items seem to have use a __category__.json in the dir
            type: 'generated-index',
            title: 'Plugin Development Guides',
            description: 'Resources for building your own plugin packages',
            keywords: ['guides'],
          },
          items: [ // All of these have a frontmatter 'title'
            {
              type: 'doc',
              id: 'developers/plugin-development'
            },
            {
              type: 'doc',
              id: 'developers/plugin-tutorial',
              label: 'Demo Experiment: PluginMindlessClicking'
            }
          ]
        },
        { // Extension Development
          type: 'category',
          label: 'Extensions',
          link: { // categories with autogenerated items seem to have use a __category__.json in the dir
            type: 'generated-index',
            title: 'Extension Development Guides',
            description: 'Resources for building your own extension packages',
            keywords: ['guides'],
          },
          items: [
            {
              type: 'doc',
              id: 'developers/extension-development'
            }
          ]
        },
        {
          type: 'doc',
          id: 'developers/documentation'
        },
      ]
    },
  ],
  referenceSidebar: [
    { // Core
      type: 'category',
      label: 'Core Modules',
      link: { // categories with autogenerated items seem to have use a __category__.json in the dir
        type: 'generated-index',
        title: 'Core Modules',
        description: 'Every module for general use with any jsPsych experiment',
        keywords: ['reference'],
      },
      items: [{type: 'autogenerated', dirName: 'reference'}]
    },
    { // Extensions
      type: 'category',
      label: 'Extensions',
      link: { // categories with autogenerated items seem to have use a __category__.json in the dir
        type: 'generated-index',
        title: 'Extension Packages',
        description: 'Every extension distributed through jsPsych',
        keywords: ['reference'],
      },
      items: [{type: 'autogenerated', dirName: 'extensions'}]
    }
  ],
  communitySidebar: [
    'support/support'
  ],
  aboutSidebar: [{type: 'autogenerated', dirName: 'about'}] // problem with loading license.md

  // pages that need sidebar home:
  // 'support/migration-v7'
  // 'support/migration-v8'

  // pages that break build:
  // 'plugins/'
  // 'newsletter'
  // 'extensions/mouse-tracking'
  // 'extensions/record-video'

  // content that needs writing:
  // 'timelines/'
  // plugins from jspsych-contrib
  // timeline tutorials
  // extension tutorials

  // pages left unused:
  // 'index'

};

export default sidebars;
